In [6]:
import pandas as pd

In [5]:
df = pd.read_csv('student_dataset_v1.csv')
df

,Student_Names,Phone_No,Gender,Math,Physics,Chemistry,Grade,ListofCourses
0,Santanika Sonkar,9.906433e+09,Male,82.0,51.0,36.0,C,B.E/B.Tech in Computer Science & Engineering
1,Swaroop Pandey,9.724400e+09,Female,42.0,46.0,40.0,D,B.E/B.Tech in Computer Science & Engineering (AI)
2,Vaijinath Sonkar,9.866358e+09,Male,36.0,55.0,48.0,D,B.E/B.Tech in Computer Science & Engineering (...
3,Roop Lal Kumari,9.657627e+09,Male,71.0,67.0,34.0,C,B.E/B.Tech in Computer Science & Engineering (...
4,Maurrya,9.804753e+09,Male,85.0,92.0,36.0,B+,B.E/B.Tech in Computer Science & Engineering (...
5,Rashid Vishwakarma,9.370509e+09,Female,20.0,58.0,97.0,C,B.E/B.Tech in Computer Science & Engineering (...
6,Gotu Rao,9.495502e+09,Male,62.0,30.0,44.0,D,B.E/B.Tech in Computer Science and Business Sy...
7,Rajen Maurya,9.955566e+09,Male,92.0,11.0,32.0,D,B.E/B.Tech in Electronic Engineering
8,Mohon Rai,9.646505e+09,Female,73.0,71.0,96.0,B+,B.E/B.Tech in Electronics and Communication En...
9,Parray Pandey,9.121453e+09,Male,12.0,60.0,19.0,F,B.E/B.Tech in Electrical Engineering
10,Anshu Kumar Gupta,9.436343e+09,Female,79.0,50.0,70.0,B,B.E/B.Tech in Mechanical Engineering
11,Nazneen Rai,9.371866e+09,Female,78.0,46.0,19.0,D,B.E/B.Tech in Aerospace Engineering
12,Abodh Divedi,9.846924e+09,Female,50.0,39.0,15.0,D,B.E/B.Tech in Civil Engineering
13,Bharatsinh Rao,9.934519e+09,Female,14.0,21.0,86.0,D,B.E/B.Tech in Automobile Engineering
14,Subhendu Devi,9.497229e+09,Female,90.0,60.0,53.0,B,B.E/B.Tech in Chemical Engineering
15,Baharul Kumari,9.798541e+09,Female,53.0,52.0,65.0,C,B.E/B.Tech in Biomedical Engineer
16,Aizaz Mishra,9.997857e+09,Female,94.0,66.0,59.0,B+,B.E/B.Tech in Petroleum Engineering
17,Ashi Pandey,9.072510e+09,Male,66.0,23.0,12.0,D,B.E/B.Tech in Mining Engineering
18,Nikhil,9.975296e+09,Male,75.0,10.0,79.0,C,B.E/B.Tech in Mechatronics
19,Maheah Mishra,9.648694e+09,Female,99.0,49.0,94.0,B+,B.E/B.Tech in Biotechnology
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isnull().sum()

Student_Names    1
Phone_No         1
Gender           1
Math             1
Physics          1
Chemistry        1
Grade            1
ListofCourses    1
dtype: int64

In [12]:
df = df.drop_duplicates()
df

,Student_Names,Phone_No,Gender,Math,Physics,Chemistry,Grade,ListofCourses
0,Santanika Sonkar,9.906433e+09,Male,82.0,51.0,36.0,C,B.E/B.Tech in Computer Science & Engineering
1,Swaroop Pandey,9.724400e+09,Female,42.0,46.0,40.0,D,B.E/B.Tech in Computer Science & Engineering (AI)
2,Vaijinath Sonkar,9.866358e+09,Male,36.0,55.0,48.0,D,B.E/B.Tech in Computer Science & Engineering (...
3,Roop Lal Kumari,9.657627e+09,Male,71.0,67.0,34.0,C,B.E/B.Tech in Computer Science & Engineering (...
4,Maurrya,9.804753e+09,Male,85.0,92.0,36.0,B+,B.E/B.Tech in Computer Science & Engineering (...
5,Rashid Vishwakarma,9.370509e+09,Female,20.0,58.0,97.0,C,B.E/B.Tech in Computer Science & Engineering (...
6,Gotu Rao,9.495502e+09,Male,62.0,30.0,44.0,D,B.E/B.Tech in Computer Science and Business Sy...
7,Rajen Maurya,9.955566e+09,Male,92.0,11.0,32.0,D,B.E/B.Tech in Electronic Engineering
8,Mohon Rai,9.646505e+09,Female,73.0,71.0,96.0,B+,B.E/B.Tech in Electronics and Communication En...
9,Parray Pandey,9.121453e+09,Male,12.0,60.0,19.0,F,B.E/B.Tech in Electrical Engineering
10,Anshu Kumar Gupta,9.436343e+09,Female,79.0,50.0,70.0,B,B.E/B.Tech in Mechanical Engineering
11,Nazneen Rai,9.371866e+09,Female,78.0,46.0,19.0,D,B.E/B.Tech in Aerospace Engineering
12,Abodh Divedi,9.846924e+09,Female,50.0,39.0,15.0,D,B.E/B.Tech in Civil Engineering
13,Bharatsinh Rao,9.934519e+09,Female,14.0,21.0,86.0,D,B.E/B.Tech in Automobile Engineering
14,Subhendu Devi,9.497229e+09,Female,90.0,60.0,53.0,B,B.E/B.Tech in Chemical Engineering
15,Baharul Kumari,9.798541e+09,Female,53.0,52.0,65.0,C,B.E/B.Tech in Biomedical Engineer
16,Aizaz Mishra,9.997857e+09,Female,94.0,66.0,59.0,B+,B.E/B.Tech in Petroleum Engineering
17,Ashi Pandey,9.072510e+09,Male,66.0,23.0,12.0,D,B.E/B.Tech in Mining Engineering
18,Nikhil,9.975296e+09,Male,75.0,10.0,79.0,C,B.E/B.Tech in Mechatronics
19,Maheah Mishra,9.648694e+09,Female,99.0,49.0,94.0,B+,B.E/B.Tech in Biotechnology
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.drop(columns=['ListofCourses'])

In [18]:
df

         Student_Names      Phone_No  Gender  Math  Physics  Chemistry Grade
0     Santanika Sonkar  9.906433e+09    Male  82.0     51.0       36.0     C
1       Swaroop Pandey  9.724400e+09  Female  42.0     46.0       40.0     D
2     Vaijinath Sonkar  9.866358e+09    Male  36.0     55.0       48.0     D
3      Roop Lal Kumari  9.657627e+09    Male  71.0     67.0       34.0     C
4              Maurrya  9.804753e+09    Male  85.0     92.0       36.0    B+
5   Rashid Vishwakarma  9.370509e+09  Female  20.0     58.0       97.0     C
6             Gotu Rao  9.495502e+09    Male  62.0     30.0       44.0     D
7         Rajen Maurya  9.955566e+09    Male  92.0     11.0       32.0     D
8            Mohon Rai  9.646505e+09  Female  73.0     71.0       96.0    B+
9        Parray Pandey  9.121453e+09    Male  12.0     60.0       19.0     F
10   Anshu Kumar Gupta  9.436343e+09  Female  79.0     50.0       70.0     B
11         Nazneen Rai  9.371866e+09  Female  78.0     46.0       19.0     D
12        Abodh Divedi  9.846924e+09  Female  50.0     39.0       15.0     D
13      Bharatsinh Rao  9.934519e+09  Female  14.0     21.0       86.0     D
14       Subhendu Devi  9.497229e+09  Female  90.0     60.0       53.0     B
15      Baharul Kumari  9.798541e+09  Female  53.0     52.0       65.0     C
16        Aizaz Mishra  9.997857e+09  Female  94.0     66.0       59.0    B+
17         Ashi Pandey  9.072510e+09    Male  66.0     23.0       12.0     D
18              Nikhil  9.975296e+09    Male  75.0     10.0       79.0     C
19       Maheah Mishra  9.648694e+09  Female  99.0     49.0       94.0    B+
20                 NaN           NaN     NaN   NaN      NaN        NaN   NaN

In [ ]:
df['ListofCourses'] = df['ListofCourses'].str.strip('/._ ') #Clean the text in this column by removing extra symbols

In [19]:
df

         Student_Names      Phone_No  Gender  Math  Physics  Chemistry Grade
0     Santanika Sonkar  9.906433e+09    Male  82.0     51.0       36.0     C
1       Swaroop Pandey  9.724400e+09  Female  42.0     46.0       40.0     D
2     Vaijinath Sonkar  9.866358e+09    Male  36.0     55.0       48.0     D
3      Roop Lal Kumari  9.657627e+09    Male  71.0     67.0       34.0     C
4              Maurrya  9.804753e+09    Male  85.0     92.0       36.0    B+
5   Rashid Vishwakarma  9.370509e+09  Female  20.0     58.0       97.0     C
6             Gotu Rao  9.495502e+09    Male  62.0     30.0       44.0     D
7         Rajen Maurya  9.955566e+09    Male  92.0     11.0       32.0     D
8            Mohon Rai  9.646505e+09  Female  73.0     71.0       96.0    B+
9        Parray Pandey  9.121453e+09    Male  12.0     60.0       19.0     F
10   Anshu Kumar Gupta  9.436343e+09  Female  79.0     50.0       70.0     B
11         Nazneen Rai  9.371866e+09  Female  78.0     46.0       19.0     D
12        Abodh Divedi  9.846924e+09  Female  50.0     39.0       15.0     D
13      Bharatsinh Rao  9.934519e+09  Female  14.0     21.0       86.0     D
14       Subhendu Devi  9.497229e+09  Female  90.0     60.0       53.0     B
15      Baharul Kumari  9.798541e+09  Female  53.0     52.0       65.0     C
16        Aizaz Mishra  9.997857e+09  Female  94.0     66.0       59.0    B+
17         Ashi Pandey  9.072510e+09    Male  66.0     23.0       12.0     D
18              Nikhil  9.975296e+09    Male  75.0     10.0       79.0     C
19       Maheah Mishra  9.648694e+09  Female  99.0     49.0       94.0    B+
20                 NaN           NaN     NaN   NaN      NaN        NaN   NaN

In [21]:
df = df.dropna(subset=['Gender'])       #remove rows with missing (NaN) values
df

         Student_Names      Phone_No  Gender  Math  Physics  Chemistry Grade
0     Santanika Sonkar  9.906433e+09    Male  82.0     51.0       36.0     C
1       Swaroop Pandey  9.724400e+09  Female  42.0     46.0       40.0     D
2     Vaijinath Sonkar  9.866358e+09    Male  36.0     55.0       48.0     D
3      Roop Lal Kumari  9.657627e+09    Male  71.0     67.0       34.0     C
4              Maurrya  9.804753e+09    Male  85.0     92.0       36.0    B+
5   Rashid Vishwakarma  9.370509e+09  Female  20.0     58.0       97.0     C
6             Gotu Rao  9.495502e+09    Male  62.0     30.0       44.0     D
7         Rajen Maurya  9.955566e+09    Male  92.0     11.0       32.0     D
8            Mohon Rai  9.646505e+09  Female  73.0     71.0       96.0    B+
9        Parray Pandey  9.121453e+09    Male  12.0     60.0       19.0     F
10   Anshu Kumar Gupta  9.436343e+09  Female  79.0     50.0       70.0     B
11         Nazneen Rai  9.371866e+09  Female  78.0     46.0       19.0     D
12        Abodh Divedi  9.846924e+09  Female  50.0     39.0       15.0     D
13      Bharatsinh Rao  9.934519e+09  Female  14.0     21.0       86.0     D
14       Subhendu Devi  9.497229e+09  Female  90.0     60.0       53.0     B
15      Baharul Kumari  9.798541e+09  Female  53.0     52.0       65.0     C
16        Aizaz Mishra  9.997857e+09  Female  94.0     66.0       59.0    B+
17         Ashi Pandey  9.072510e+09    Male  66.0     23.0       12.0     D
18              Nikhil  9.975296e+09    Male  75.0     10.0       79.0     C
19       Maheah Mishra  9.648694e+09  Female  99.0     49.0       94.0    B+

In [24]:
df.dtypes

Student_Names        str
Phone_No         float64
Gender               str
Math             float64
Physics          float64
Chemistry        float64
Grade                str
dtype: object

In [26]:
df['Math'] = df['Math'].fillna(df['Math'].mean())
df

         Student_Names      Phone_No  Gender  Math  Physics  Chemistry Grade
0     Santanika Sonkar  9.906433e+09    Male  82.0     51.0       36.0     C
1       Swaroop Pandey  9.724400e+09  Female  42.0     46.0       40.0     D
2     Vaijinath Sonkar  9.866358e+09    Male  36.0     55.0       48.0     D
3      Roop Lal Kumari  9.657627e+09    Male  71.0     67.0       34.0     C
4              Maurrya  9.804753e+09    Male  85.0     92.0       36.0    B+
5   Rashid Vishwakarma  9.370509e+09  Female  20.0     58.0       97.0     C
6             Gotu Rao  9.495502e+09    Male  62.0     30.0       44.0     D
7         Rajen Maurya  9.955566e+09    Male  92.0     11.0       32.0     D
8            Mohon Rai  9.646505e+09  Female  73.0     71.0       96.0    B+
9        Parray Pandey  9.121453e+09    Male  12.0     60.0       19.0     F
10   Anshu Kumar Gupta  9.436343e+09  Female  79.0     50.0       70.0     B
11         Nazneen Rai  9.371866e+09  Female  78.0     46.0       19.0     D
12        Abodh Divedi  9.846924e+09  Female  50.0     39.0       15.0     D
13      Bharatsinh Rao  9.934519e+09  Female  14.0     21.0       86.0     D
14       Subhendu Devi  9.497229e+09  Female  90.0     60.0       53.0     B
15      Baharul Kumari  9.798541e+09  Female  53.0     52.0       65.0     C
16        Aizaz Mishra  9.997857e+09  Female  94.0     66.0       59.0    B+
17         Ashi Pandey  9.072510e+09    Male  66.0     23.0       12.0     D
18              Nikhil  9.975296e+09    Male  75.0     10.0       79.0     C
19       Maheah Mishra  9.648694e+09  Female  99.0     49.0       94.0    B+

In [35]:
print(df.head()) 
df.to_csv("cleaned_student_dataset.csv", index=False)

      Student_Names      Phone_No  Gender  Math  Physics  Chemistry Grade
0  Santanika Sonkar  9.906433e+09    Male  82.0     51.0       36.0     C
1    Swaroop Pandey  9.724400e+09  Female  42.0     46.0       40.0     D
2  Vaijinath Sonkar  9.866358e+09    Male  36.0     55.0       48.0     D
3   Roop Lal Kumari  9.657627e+09    Male  71.0     67.0       34.0     C
4           Maurrya  9.804753e+09    Male  85.0     92.0       36.0    B+

In [31]:
print(df.tail())

     Student_Names      Phone_No  Gender  Math  Physics  Chemistry Grade
15  Baharul Kumari  9.798541e+09  Female  53.0     52.0       65.0     C
16    Aizaz Mishra  9.997857e+09  Female  94.0     66.0       59.0    B+
17     Ashi Pandey  9.072510e+09    Male  66.0     23.0       12.0     D
18          Nikhil  9.975296e+09    Male  75.0     10.0       79.0     C
19   Maheah Mishra  9.648694e+09  Female  99.0     49.0       94.0    B+